name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Build back
        run: |
          gradle build --stacktrace
      - name: Download front dependancies
        run: |
          mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get \
              -DremoteRepositories=https://packagecloud.io/sarahBuisson/snapshot/maven2/ \
              -Dartifact=org.jeasy:easy-rules-core-npm:3.2.4-snapshot
          mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get \
              -DremoteRepositories=https://packagecloud.io/sarahBuisson/snapshot/maven2/ \
              -Dartifact=org.jeasy:easy-rules-api-npm:3.2.4-snapshot

          cd website
          npm install -g @angular/cli
          npm install -g angular-cli-ghpages
          npm install tone
          yarn install
          cd ./node_modules/tone
          npm run ts:build
          npm run webpack:build"
      - name: list front dependancies downloaded
        run: |
          cd website
          echo "npm package installed:"
          find ./node_modules -type f -name 'package.json' |sort
          echo "npm package installed in gamRules:"
          find ./node_modules/gameRules -type f -name 'package.json' |sort
          ls -lrt ./node_modules/tone
      - name: Build front
        run: |
          cd website
          ng build --base-href /labyrinth-game/
          ls dist
          cp ./dist/website-angular/index.html ./dist/website-angular/404.html
      - name: extract build version
        run: |
          gradle generatePomFileForKotlinMultiplatformPublication
          echo "::set-env name=BUILD_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -f M3/build/publications/kotlinMultiplatform/pom-default.xml -DforceStdout)"
          echo "::set-env name=BUILD_ARTIFACT_ID::$(mvn help:evaluate -Dexpression=project.artifactId -q -f M3/build/publications/kotlinMultiplatform/pom-default.xml -DforceStdout)"
          echo "::set-env name=BUILD_GROUP_ID::$(mvn help:evaluate -Dexpression=project.groupId -q -f M3/build/publications/kotlinMultiplatform/pom-default.xml -DforceStdout)"
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: website/dist/website-angular
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
