name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Build back
        run: |
          gradle build --stacktrace -i
      - name: Build back lib for front
        run: |
          gradle packJsNpmToMaven
      - name: Build front load dep
        run: |
          cd website
          yarn install
      - name: fix undownload dep
        run: |
          cd website
          cp -R node_modules/easy-rules-api/ node_modules/game/node_modules/easy-rules-api
          cp -R node_modules/easy-rules-core/ node_modules/game/node_modules/easy-rules-core
          cp -R node_modules/easy-rules-kotlin-easy-rules-core node_modules/game/node_modules/easy-rules-kotlin-easy-rules-core
          cp -R node_modules/easy-rules-kotlin-easy-rules-api node_modules/game/node_modules/easy-rules-kotlin-easy-rules-api
          ls node_modules/game/node_modules/easy-rules-kotlin-easy-rules-core
      - name: Build front
        run: |
          cd website
          yarn run buildDev
      - name: extract build version
        run: |
          gradle generatePomFileForKotlinMultiplatformPublication
          echo "::set-env name=BUILD_VERSION::$(mvn help:evaluate -Dexpression=project.version -q -f M3/build/publications/kotlinMultiplatform/pom-default.xml -DforceStdout)"
          echo "::set-env name=BUILD_ARTIFACT_ID::$(mvn help:evaluate -Dexpression=project.artifactId -q -f M3/build/publications/kotlinMultiplatform/pom-default.xml -DforceStdout)"
          echo "::set-env name=BUILD_GROUP_ID::$(mvn help:evaluate -Dexpression=project.groupId -q -f M3/build/publications/kotlinMultiplatform/pom-default.xml -DforceStdout)"
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: website/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}